import type { NextPage } from 'next'
import Head from 'next/head'
import NewPosts from '../components/main/NewPosts'
import RecentPosts from '../components/main/RecentPosts'
import PopularPosts from '../components/main/PopularPosts'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <NewPosts />
        <RecentPosts />
        <PopularPosts />
      </main>
    </>
  )
}

export default Home
